
var not =
  ["Midway Dodge II","We Wash",
  "Western Avenue Nissan",
  "Rogers Auto Group",
  "Auto's R Us",
  "West Loop Auto Body",
  "Honda City",
  "Advance Auto Parts",
  "Marquette Frame & Wheel Alignment",
  "C & J Auto Parts",
  "State Street Hand Car Wash",
  "Aaron Auto Glass",
  "Strictly By Hand",
  "Car Credit Center",
  "Midas",
  "Franklin Motor Credit",
  "Euro Collision",
  "Oil Express",
  "Advance Auto Parts",
  "Car Outlet",
  "Autozone",
"Elgin Hyundai",
"Biggers Mazda",
"NAPA Auto Parts",
"Woody Buick GMC",
"Discount Tire",
"Ron Hopkins Ford",
"Kellenberger Auto Service",
"K & S Automotive",
"Renew Auto Sales",
"Elgin Toyota",
"Brittain's Express Oil & Lube",
"Jerry Biggers Chevrolet",
"McGrath Nissan",
"Gerber Collision & Glass",
"Valvoline Instant Oil Change",
"Autozone",
"Pep Boys Auto Service & Tire",
"Chihuahua Tire",
"Gerber Collision & Glass",
"Feeny Chrysler Jeep Dodge",
"Spring Hill Ford",
"Merlin Muffler & Brake",
"Tuffy Auto Service Centers",
"Piemonte's Dundee Chevrolet",
"Sears Auto Center",
"Elgin Super Auto Parts",
"Affordable Autos",
"Tom's Auto Clinic",
"Copart",
"Superior Car Credit",
"Auto Truck Group",
"Broadway Tire & Firestone",
"Jiffy Lube",
"Lube Express",
"TLC Handwash & Detail",
"McGrath Honda",
"Itw Shakeproof",
"Rosen Kia of Elgin",
"Royal Car Sales",
"Firestone Complete Auto Care",
"Pro Wash Express",
"Forrest Auto Body",
"Streit's Auto",
"Car-X Auto Service",
"Landmark Car Wash of Elgin",
"Pro Paintless Dent Repair",
"null",
"Precision Body Works",
"La Fox Oil & Lube",
"Fornarelli Motorsports",
"Amigo Transmissions Plus",
"National Tire & Battery",
"Elgin Industries",
"Carquest Auto Parts",
"Kane County Motor Sports",
"Boss Automotive",
"Economical Tires",
"Wittenstein",
"Espo's Auto Care",
"Key West Auto Spa",
"Ken's Auto",
"J & R Auto Salon",
"BBK Motorsports",
"Velasquez & Sons Mufflers IV Less",
"Elgin Car Wash",
"McLean Auto Repair",
"Braasch Automotive",
"Lubepro's",
"Lube Pro's",
"Oil Masters",
"East Dundee Express Car Wash",
"Torres Auto Repair",
"Meineke Car Care Center",
"Lemus Auto Repair",
"Chicago Street Auto Body",
"Dundee Automotive",
"Car-X Tire & Auto",
"One Gr8 Car Wash",
"Swift Car Wash",
"Merlin 200 000 Mile Shop",
"Bartlett Automotive",
"Biggers Mitsubishi",
"Dundee Collision",
"Clean Stream Car Wash",
"J Martin Auto Service",
"Dnr Consulting",
"Spring Hill Auto Body",
"Jam Auto Rebuilder",
"R & L Auto Repair",
"Harlow at Rosen KIA",
"Merlin 200000 Miles Shop",
"CARSTAR Auto Body Repair Experts",
"Mr Carwash",
"Midwestern Auto Parts",
"Red Mist Automotive",
"Car Smart Automotive",
"Babb's Auto Enterprise",
"Lord's Auto Care Service"
]

module.exports = {
  not: not
};
